import { defineConfig } from "vite-plus";

export default defineConfig({
  // Bundling via tsdown
  pack: {
    entry: { index: "src/functions/messages.ts" },
    format: "cjs",
    platform: "node",
    fixedExtension: false,
    deps: {
      // tsdown <0.23 compatibility: resolve external dependency subpaths.
      // Remove to preserve subpath imports as written (the new default).
      // https://tsdown.dev/options/dependencies#deps-resolvedepsubpath
      resolveDepSubpath: true,
      neverBundle: [
        // Provided by the Azure Functions runtime, keep external
        "@azure/functions",
        // node_modules are shipped with the deployment, keep external
        "botbuilder",
      ],
    },
  },

  // Linting via Oxlint
  lint: {
    ignorePatterns: ["dist/**", "node_modules/**"],
  },

  // Formatting via Oxfmt
  fmt: {
    // Generated by release-please; formatting it would keep producing diffs on every release
    ignorePatterns: ["CHANGELOG.md"],
  },

  // Testing via Vitest
  test: {
    include: ["src/**/*.test.ts"],
    passWithNoTests: true,
  },
});
